2023-12-11 22:05:43,243 - Cell - INFO - server: creating listener on grpc://0:8002
2023-12-11 22:05:43,251 - Cell - INFO - server: created backbone external listener for grpc://0:8002
2023-12-11 22:05:43,252 - ConnectorManager - INFO - 436: Try start_listener Listener resources: {'secure': False, 'host': 'localhost'}
2023-12-11 22:05:43,253 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00002 PASSIVE tcp://0:56994] is starting
2023-12-11 22:05:43,755 - Cell - INFO - server: created backbone internal listener for tcp://localhost:56994
2023-12-11 22:05:43,755 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00001 PASSIVE grpc://0:8002] is starting
2023-12-11 22:05:43,791 - nvflare.fuel.hci.server.hci - INFO - Starting Admin Server server1 on Port 8003
2023-12-11 22:05:43,791 - root - INFO - Server started
2023-12-11 22:05:43,792 - nvflare.fuel.f3.drivers.aio_grpc_driver.Server - INFO - added secure port at 0.0.0.0:8002
2023-12-11 22:05:43,862 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - SERVER: listening on [CH00001 PASSIVE grpc://0:8002]
2023-12-11 22:05:50,022 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f472a718700>: Failed to establish a new connection: [Errno -2] Name or service not known')': /api/v1/heartbeat
2023-12-11 22:06:06,418 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f472a68d970>: Failed to establish a new connection: [Errno -2] Name or service not known')': /api/v1/heartbeat
2023-12-11 22:06:22,831 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f472a68dd30>: Failed to establish a new connection: [Errno -2] Name or service not known')': /api/v1/heartbeat
2023-12-11 22:06:39,247 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f472a7189a0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /api/v1/heartbeat
2023-12-11 22:06:55,658 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f472a718e80>: Failed to establish a new connection: [Errno -2] Name or service not known')': /api/v1/heartbeat
2023-12-11 22:07:12,064 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f472a68d940>: Failed to establish a new connection: [Errno -2] Name or service not known')': /api/v1/heartbeat
2023-12-11 22:07:28,492 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f472a6af100>: Failed to establish a new connection: [Errno -2] Name or service not known')': /api/v1/heartbeat
2023-12-11 22:07:44,892 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f472a6af4c0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /api/v1/heartbeat
2023-12-11 22:08:01,287 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f472a6af880>: Failed to establish a new connection: [Errno -2] Name or service not known')': /api/v1/heartbeat
2023-12-11 22:08:17,675 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f472a6afc40>: Failed to establish a new connection: [Errno -2] Name or service not known')': /api/v1/heartbeat
2023-12-11 22:08:34,078 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f472a6affd0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /api/v1/heartbeat
