2024-01-16 21:00:48,025 - Cell - INFO - site-1: created backbone external connector to grpc://host.docker.internal:8002
2024-01-16 21:00:48,025 - ConnectorManager - INFO - 118: Try start_listener Listener resources: {'secure': False, 'host': 'localhost'}
2024-01-16 21:00:48,027 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00002 PASSIVE tcp://0:44011] is starting
2024-01-16 21:00:48,530 - Cell - INFO - site-1: created backbone internal listener for tcp://localhost:44011
2024-01-16 21:00:48,531 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00001 ACTIVE grpc://host.docker.internal:8002] is starting
2024-01-16 21:00:48,535 - FederatedClient - INFO - Wait for engine to be created.
2024-01-16 21:00:48,572 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-16 21:00:49,010 - FederatedClient - INFO - Successfully registered client:site-1 for project example_project. Token:532c4ae3-a316-4753-9c9f-ae3862069b69 SSID:ebc6125d-0a56-4688-9b08-355fe9e4d61a
2024-01-16 21:00:49,017 - FederatedClient - INFO - Got engine after 0.48221635818481445 seconds
2024-01-16 21:00:49,017 - FederatedClient - INFO - Got the new primary SP: grpc://host.docker.internal:8002
2024-01-17 16:16:34,945 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00002 N/A => host.docker.internal:8002 SSL N/A] Error: Socket closed
2024-01-17 16:16:35,016 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00002 N/A => host.docker.internal:8002 SSL N/A]: in aio_ctx: done read_loop
2024-01-17 16:16:35,018 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 16:16:35,025 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00002 Not Connected] closed
2024-01-17 16:16:36,081 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 16:16:36,171 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00003 Not Connected] Error: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.168.65.254:8002: Socket closed
2024-01-17 16:16:36,172 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00003 Not Connected]: in aio_ctx: done read_loop
2024-01-17 16:16:36,172 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 16:16:36,239 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00003 Not Connected] closed
2024-01-17 16:16:38,252 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 16:16:38,258 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00004 Not Connected] Error: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.168.65.254:8002: Socket closed
2024-01-17 16:16:38,258 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00004 Not Connected]: in aio_ctx: done read_loop
2024-01-17 16:16:38,258 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 16:16:38,447 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00004 Not Connected] closed
2024-01-17 16:27:53,699 - Cell - INFO - site-1: created backbone external connector to grpc://host.docker.internal:8002
2024-01-17 16:27:53,699 - ConnectorManager - INFO - 117: Try start_listener Listener resources: {'secure': False, 'host': 'localhost'}
2024-01-17 16:27:53,701 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00002 PASSIVE tcp://0:47659] is starting
2024-01-17 16:27:54,203 - Cell - INFO - site-1: created backbone internal listener for tcp://localhost:47659
2024-01-17 16:27:54,203 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00001 ACTIVE grpc://host.docker.internal:8002] is starting
2024-01-17 16:27:54,205 - FederatedClient - INFO - Wait for engine to be created.
2024-01-17 16:27:54,221 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 16:27:54,685 - FederatedClient - INFO - Successfully registered client:site-1 for project example_project. Token:363c03d1-369f-4626-b710-ba74869aadde SSID:ebc6125d-0a56-4688-9b08-355fe9e4d61a
2024-01-17 16:27:54,688 - FederatedClient - INFO - Got engine after 0.48221898078918457 seconds
2024-01-17 16:27:54,689 - FederatedClient - INFO - Got the new primary SP: grpc://host.docker.internal:8002
2024-01-17 17:17:21,026 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00002 N/A => host.docker.internal:8002 SSL N/A] Error: Socket closed
2024-01-17 17:17:21,053 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00002 N/A => host.docker.internal:8002 SSL N/A]: in aio_ctx: done read_loop
2024-01-17 17:17:21,054 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:17:21,057 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00002 Not Connected] closed
2024-01-17 17:17:22,102 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:17:22,146 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00003 Not Connected] Error: failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.65.254:8002: Failed to connect to remote host: Connection refused
2024-01-17 17:17:22,147 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00003 Not Connected]: in aio_ctx: done read_loop
2024-01-17 17:17:22,147 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:17:22,266 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00003 Not Connected] closed
2024-01-17 17:17:24,286 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:17:24,289 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00004 Not Connected] Error: failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.65.254:8002: Failed to connect to remote host: Connection refused
2024-01-17 17:17:24,290 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00004 Not Connected]: in aio_ctx: done read_loop
2024-01-17 17:17:24,290 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:17:24,479 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00004 Not Connected] closed
2024-01-17 17:17:28,494 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:17:28,497 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00005 Not Connected] Error: failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.65.254:8002: Failed to connect to remote host: Connection refused
2024-01-17 17:17:28,498 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00005 Not Connected]: in aio_ctx: done read_loop
2024-01-17 17:17:28,498 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:17:28,687 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00005 Not Connected] closed
2024-01-17 17:17:28,688 - nvflare.fuel.f3.sfm.conn_manager - INFO - Retrying [CH00001 ACTIVE grpc://host.docker.internal:8002] in 8 seconds
2024-01-17 17:17:28,783 - Cell - WARNING - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] no connection to server
2024-01-17 17:17:28,783 - Cell - ERROR - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] cannot send to 'server': target_unreachable
2024-01-17 17:17:28,783 - Communicator - ERROR - heartbeat error: target_unreachable
2024-01-17 17:17:36,711 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:17:36,716 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00006 Not Connected] Error: failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.65.254:8002: Failed to connect to remote host: Connection refused
2024-01-17 17:17:36,716 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00006 Not Connected]: in aio_ctx: done read_loop
2024-01-17 17:17:36,717 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:17:36,907 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00006 Not Connected] closed
2024-01-17 17:17:36,907 - nvflare.fuel.f3.sfm.conn_manager - INFO - Retrying [CH00001 ACTIVE grpc://host.docker.internal:8002] in 10 seconds
2024-01-17 17:17:38,793 - Cell - WARNING - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] no connection to server
2024-01-17 17:17:38,794 - Cell - ERROR - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] cannot send to 'server': target_unreachable
2024-01-17 17:17:38,794 - Communicator - ERROR - heartbeat error: target_unreachable
2024-01-17 17:17:46,929 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:17:46,942 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00007 Not Connected] Error: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.168.65.254:8002: Socket closed
2024-01-17 17:17:46,943 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00007 Not Connected]: in aio_ctx: done read_loop
2024-01-17 17:17:46,943 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:17:47,124 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00007 Not Connected] closed
2024-01-17 17:17:47,125 - nvflare.fuel.f3.sfm.conn_manager - INFO - Retrying [CH00001 ACTIVE grpc://host.docker.internal:8002] in 10 seconds
2024-01-17 17:17:48,804 - Cell - WARNING - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] no connection to server
2024-01-17 17:17:48,805 - Cell - ERROR - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] cannot send to 'server': target_unreachable
2024-01-17 17:17:48,805 - Communicator - ERROR - heartbeat error: target_unreachable
2024-01-17 17:17:57,151 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:17:57,158 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00008 Not Connected] Error: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.168.65.254:8002: Socket closed
2024-01-17 17:17:57,158 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00008 Not Connected]: in aio_ctx: done read_loop
2024-01-17 17:17:57,159 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:17:57,346 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00008 Not Connected] closed
2024-01-17 17:17:57,347 - nvflare.fuel.f3.sfm.conn_manager - INFO - Retrying [CH00001 ACTIVE grpc://host.docker.internal:8002] in 10 seconds
2024-01-17 17:17:58,816 - Cell - WARNING - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] no connection to server
2024-01-17 17:17:58,816 - Cell - ERROR - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] cannot send to 'server': target_unreachable
2024-01-17 17:17:58,817 - Communicator - ERROR - heartbeat error: target_unreachable
2024-01-17 17:18:07,371 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:18:07,375 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00009 Not Connected] Error: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.168.65.254:8002: Socket closed
2024-01-17 17:18:07,376 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00009 Not Connected]: in aio_ctx: done read_loop
2024-01-17 17:18:07,376 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:18:07,564 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00009 Not Connected] closed
2024-01-17 17:18:07,564 - nvflare.fuel.f3.sfm.conn_manager - INFO - Retrying [CH00001 ACTIVE grpc://host.docker.internal:8002] in 10 seconds
2024-01-17 17:18:08,827 - Cell - WARNING - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] no connection to server
2024-01-17 17:18:08,828 - Cell - ERROR - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] cannot send to 'server': target_unreachable
2024-01-17 17:18:08,828 - Communicator - ERROR - heartbeat error: target_unreachable
2024-01-17 17:18:17,588 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:18:17,592 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00010 Not Connected] Error: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.168.65.254:8002: Socket closed
2024-01-17 17:18:17,593 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00010 Not Connected]: in aio_ctx: done read_loop
2024-01-17 17:18:17,593 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:18:17,782 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00010 Not Connected] closed
2024-01-17 17:18:17,782 - nvflare.fuel.f3.sfm.conn_manager - INFO - Retrying [CH00001 ACTIVE grpc://host.docker.internal:8002] in 10 seconds
2024-01-17 17:18:18,839 - Cell - WARNING - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] no connection to server
2024-01-17 17:18:18,839 - Cell - ERROR - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] cannot send to 'server': target_unreachable
2024-01-17 17:18:18,840 - Communicator - ERROR - heartbeat error: target_unreachable
2024-01-17 17:18:27,805 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:18:27,810 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00011 Not Connected] Error: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.168.65.254:8002: Socket closed
2024-01-17 17:18:27,811 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00011 Not Connected]: in aio_ctx: done read_loop
2024-01-17 17:18:27,811 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:18:28,000 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00011 Not Connected] closed
2024-01-17 17:18:28,001 - nvflare.fuel.f3.sfm.conn_manager - INFO - Retrying [CH00001 ACTIVE grpc://host.docker.internal:8002] in 10 seconds
2024-01-17 17:18:28,848 - Cell - WARNING - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] no connection to server
2024-01-17 17:18:28,849 - Cell - ERROR - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] cannot send to 'server': target_unreachable
2024-01-17 17:18:28,849 - Communicator - ERROR - heartbeat error: target_unreachable
2024-01-17 17:18:38,024 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:18:38,030 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00012 Not Connected] Error: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.168.65.254:8002: Socket closed
2024-01-17 17:18:38,030 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00012 Not Connected]: in aio_ctx: done read_loop
2024-01-17 17:18:38,030 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:18:38,219 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00012 Not Connected] closed
2024-01-17 17:18:38,219 - nvflare.fuel.f3.sfm.conn_manager - INFO - Retrying [CH00001 ACTIVE grpc://host.docker.internal:8002] in 10 seconds
2024-01-17 17:18:38,859 - Cell - WARNING - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] no connection to server
2024-01-17 17:18:38,859 - Cell - ERROR - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] cannot send to 'server': target_unreachable
2024-01-17 17:18:38,860 - Communicator - ERROR - heartbeat error: target_unreachable
2024-01-17 17:18:48,241 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:18:48,246 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00013 Not Connected] Error: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.168.65.254:8002: Socket closed
2024-01-17 17:18:48,247 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00013 Not Connected]: in aio_ctx: done read_loop
2024-01-17 17:18:48,247 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:18:48,436 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00013 Not Connected] closed
2024-01-17 17:18:48,437 - nvflare.fuel.f3.sfm.conn_manager - INFO - Retrying [CH00001 ACTIVE grpc://host.docker.internal:8002] in 10 seconds
2024-01-17 17:18:48,870 - Cell - WARNING - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] no connection to server
2024-01-17 17:18:48,870 - Cell - ERROR - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] cannot send to 'server': target_unreachable
2024-01-17 17:18:48,871 - Communicator - ERROR - heartbeat error: target_unreachable
2024-01-17 17:18:58,458 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:24:00,599 - Cell - INFO - site-1: created backbone external connector to grpc://host.docker.internal:8002
2024-01-17 17:24:00,599 - ConnectorManager - INFO - 118: Try start_listener Listener resources: {'secure': False, 'host': 'localhost'}
2024-01-17 17:24:00,601 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00002 PASSIVE tcp://0:59195] is starting
2024-01-17 17:24:01,103 - Cell - INFO - site-1: created backbone internal listener for tcp://localhost:59195
2024-01-17 17:24:01,103 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00001 ACTIVE grpc://host.docker.internal:8002] is starting
2024-01-17 17:24:01,105 - FederatedClient - INFO - Wait for engine to be created.
2024-01-17 17:24:01,121 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:24:01,585 - FederatedClient - INFO - Successfully registered client:site-1 for project example_project. Token:2661b7dc-55e0-4ad1-aa9b-74621e6b273b SSID:ebc6125d-0a56-4688-9b08-355fe9e4d61a
2024-01-17 17:24:01,590 - FederatedClient - INFO - Got engine after 0.4845001697540283 seconds
2024-01-17 17:24:01,591 - FederatedClient - INFO - Got the new primary SP: grpc://host.docker.internal:8002
2024-01-17 17:31:10,647 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00002 N/A => host.docker.internal:8002 SSL N/A] Error: Socket closed
2024-01-17 17:31:10,649 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00002 N/A => host.docker.internal:8002 SSL N/A]: in aio_ctx: done read_loop
2024-01-17 17:31:10,649 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:31:10,650 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00002 Not Connected] closed
2024-01-17 17:31:11,659 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:31:11,663 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00003 Not Connected] Error: failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.65.254:8002: Failed to connect to remote host: Connection refused
2024-01-17 17:31:11,663 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00003 Not Connected]: in aio_ctx: done read_loop
2024-01-17 17:31:11,664 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:31:11,853 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00003 Not Connected] closed
2024-01-17 17:31:12,309 - Cell - WARNING - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] no connection to server
2024-01-17 17:31:12,310 - Cell - ERROR - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] cannot send to 'server': target_unreachable
2024-01-17 17:31:12,310 - Communicator - ERROR - heartbeat error: target_unreachable
2024-01-17 17:31:13,863 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:31:13,866 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00004 Not Connected] Error: failed to connect to all addresses; last error: UNKNOWN: ipv4:192.168.65.254:8002: Failed to connect to remote host: Connection refused
2024-01-17 17:31:13,866 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00004 Not Connected]: in aio_ctx: done read_loop
2024-01-17 17:31:13,867 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:31:14,057 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00004 Not Connected] closed
2024-01-17 17:31:18,070 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:31:18,076 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00005 Not Connected] Error: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.168.65.254:8002: Socket closed
2024-01-17 17:31:18,077 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00005 Not Connected]: in aio_ctx: done read_loop
2024-01-17 17:31:18,077 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:31:18,265 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00005 Not Connected] closed
2024-01-17 17:31:18,266 - nvflare.fuel.f3.sfm.conn_manager - INFO - Retrying [CH00001 ACTIVE grpc://host.docker.internal:8002] in 8 seconds
2024-01-17 17:31:22,319 - Cell - WARNING - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] no connection to server
2024-01-17 17:31:22,320 - Cell - ERROR - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] cannot send to 'server': target_unreachable
2024-01-17 17:31:22,320 - Communicator - ERROR - heartbeat error: target_unreachable
2024-01-17 17:31:26,284 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:31:26,290 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00006 Not Connected] Error: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.168.65.254:8002: Socket closed
2024-01-17 17:31:26,290 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00006 Not Connected]: in aio_ctx: done read_loop
2024-01-17 17:31:26,290 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:31:26,480 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00006 Not Connected] closed
2024-01-17 17:31:26,481 - nvflare.fuel.f3.sfm.conn_manager - INFO - Retrying [CH00001 ACTIVE grpc://host.docker.internal:8002] in 10 seconds
2024-01-17 17:31:32,330 - Cell - WARNING - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] no connection to server
2024-01-17 17:31:32,330 - Cell - ERROR - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] cannot send to 'server': target_unreachable
2024-01-17 17:31:32,331 - Communicator - ERROR - heartbeat error: target_unreachable
2024-01-17 17:31:36,502 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:31:36,507 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Connection [CN00007 Not Connected] Error: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.168.65.254:8002: Socket closed
2024-01-17 17:31:36,507 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - [CN00007 Not Connected]: in aio_ctx: done read_loop
2024-01-17 17:31:36,507 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioStreamSession - INFO - Closed GRPC Channel
2024-01-17 17:31:36,697 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - CLIENT: connection [CN00007 Not Connected] closed
2024-01-17 17:31:36,698 - nvflare.fuel.f3.sfm.conn_manager - INFO - Retrying [CH00001 ACTIVE grpc://host.docker.internal:8002] in 10 seconds
2024-01-17 17:31:42,340 - Cell - WARNING - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] no connection to server
2024-01-17 17:31:42,340 - Cell - ERROR - [ME=site-1 O=? D=server F=? T=? CH=task TP=heart_beat] cannot send to 'server': target_unreachable
2024-01-17 17:31:42,340 - Communicator - ERROR - heartbeat error: target_unreachable
2024-01-17 17:31:46,719 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:56:05,760 - Cell - INFO - site-1: created backbone external connector to grpc://host.docker.internal:8002
2024-01-17 17:56:05,761 - ConnectorManager - INFO - 118: Try start_listener Listener resources: {'secure': False, 'host': 'localhost'}
2024-01-17 17:56:05,762 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00002 PASSIVE tcp://0:50173] is starting
2024-01-17 17:56:06,264 - Cell - INFO - site-1: created backbone internal listener for tcp://localhost:50173
2024-01-17 17:56:06,264 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00001 ACTIVE grpc://host.docker.internal:8002] is starting
2024-01-17 17:56:06,266 - FederatedClient - INFO - Wait for engine to be created.
2024-01-17 17:56:06,285 - nvflare.fuel.f3.drivers.aio_grpc_driver.AioGrpcDriver - INFO - created secure channel at host.docker.internal:8002
2024-01-17 17:56:06,745 - FederatedClient - INFO - Successfully registered client:site-1 for project example_project. Token:ec4d017b-e70c-41f9-9db9-7a2352d0490c SSID:ebc6125d-0a56-4688-9b08-355fe9e4d61a
2024-01-17 17:56:06,747 - FederatedClient - INFO - Got engine after 0.48142552375793457 seconds
2024-01-17 17:56:06,748 - FederatedClient - INFO - Got the new primary SP: grpc://host.docker.internal:8002
2024-01-17 18:05:25,107 - ClientEngine - INFO - Starting client app. rank: 0
2024-01-17 18:05:25,142 - ProcessExecutor - INFO - Worker child process ID: 861
2024-01-17 18:05:25,143 - ProcessExecutor - INFO - run (bbe2962a-2249-40ee-8639-d8c819403540): waiting for child worker process to finish.
2024-01-17 18:05:36,701 - ProcessExecutor - INFO - run (bbe2962a-2249-40ee-8639-d8c819403540): child worker process finished with RC 0
